// Generated by gencpp from file test_gui/SrvTransform.msg
// DO NOT EDIT!


#ifndef TEST_GUI_MESSAGE_SRVTRANSFORM_H
#define TEST_GUI_MESSAGE_SRVTRANSFORM_H

#include <ros/service_traits.h>


#include <test_gui/SrvTransformRequest.h>
#include <test_gui/SrvTransformResponse.h>


namespace test_gui
{

struct SrvTransform
{

typedef SrvTransformRequest Request;
typedef SrvTransformResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SrvTransform
} // namespace test_gui


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test_gui::SrvTransform > {
  static const char* value()
  {
    return "77978c20bc039a00bc9de385da9b5ab9";
  }

  static const char* value(const ::test_gui::SrvTransform&) { return value(); }
};

template<>
struct DataType< ::test_gui::SrvTransform > {
  static const char* value()
  {
    return "test_gui/SrvTransform";
  }

  static const char* value(const ::test_gui::SrvTransform&) { return value(); }
};


// service_traits::MD5Sum< ::test_gui::SrvTransformRequest> should match 
// service_traits::MD5Sum< ::test_gui::SrvTransform > 
template<>
struct MD5Sum< ::test_gui::SrvTransformRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test_gui::SrvTransform >::value();
  }
  static const char* value(const ::test_gui::SrvTransformRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_gui::SrvTransformRequest> should match 
// service_traits::DataType< ::test_gui::SrvTransform > 
template<>
struct DataType< ::test_gui::SrvTransformRequest>
{
  static const char* value()
  {
    return DataType< ::test_gui::SrvTransform >::value();
  }
  static const char* value(const ::test_gui::SrvTransformRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test_gui::SrvTransformResponse> should match 
// service_traits::MD5Sum< ::test_gui::SrvTransform > 
template<>
struct MD5Sum< ::test_gui::SrvTransformResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test_gui::SrvTransform >::value();
  }
  static const char* value(const ::test_gui::SrvTransformResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_gui::SrvTransformResponse> should match 
// service_traits::DataType< ::test_gui::SrvTransform > 
template<>
struct DataType< ::test_gui::SrvTransformResponse>
{
  static const char* value()
  {
    return DataType< ::test_gui::SrvTransform >::value();
  }
  static const char* value(const ::test_gui::SrvTransformResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_GUI_MESSAGE_SRVTRANSFORM_H
