// Generated by gencpp from file test_gui/SrvTransformResponse.msg
// DO NOT EDIT!


#ifndef TEST_GUI_MESSAGE_SRVTRANSFORMRESPONSE_H
#define TEST_GUI_MESSAGE_SRVTRANSFORMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_gui
{
template <class ContainerAllocator>
struct SrvTransformResponse_
{
  typedef SrvTransformResponse_<ContainerAllocator> Type;

  SrvTransformResponse_()
    : result(false)  {
    }
  SrvTransformResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::test_gui::SrvTransformResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_gui::SrvTransformResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SrvTransformResponse_

typedef ::test_gui::SrvTransformResponse_<std::allocator<void> > SrvTransformResponse;

typedef boost::shared_ptr< ::test_gui::SrvTransformResponse > SrvTransformResponsePtr;
typedef boost::shared_ptr< ::test_gui::SrvTransformResponse const> SrvTransformResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_gui::SrvTransformResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_gui::SrvTransformResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test_gui

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::test_gui::SrvTransformResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_gui::SrvTransformResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_gui::SrvTransformResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_gui::SrvTransformResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_gui::SrvTransformResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_gui::SrvTransformResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_gui::SrvTransformResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::test_gui::SrvTransformResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::test_gui::SrvTransformResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_gui/SrvTransformResponse";
  }

  static const char* value(const ::test_gui::SrvTransformResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_gui::SrvTransformResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n\
\n\
\n\
";
  }

  static const char* value(const ::test_gui::SrvTransformResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_gui::SrvTransformResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SrvTransformResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_gui::SrvTransformResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_gui::SrvTransformResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_GUI_MESSAGE_SRVTRANSFORMRESPONSE_H
