#!/usr/bin/env bash
# check updates
sudo apt-get update
sudo apt-get upgrade -y
# set up source list
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
# set up keys
sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116
# check update to date
sudo apt-get update
# install ros kinetic
sudo apt-get install ros-kinetic-desktop-full -y
# Initialize rosdep
sudo rosdep init
# set up environment
echo "source /opt/ros/kinetic/setup.bash" >> ~/.bashrc
source ~/.bashrc
# install dependencies
sudo apt-get install python-rosinstall python-rosinstall-generator python-wstool build-essential -y

sudo apt-get install xterm
sudo apt-get install subversion 
#soem released for ROS
sudo apt install ros-kinetic-soem
