// Generated by gencpp from file pick_place/SrvTransform.msg
// DO NOT EDIT!


#ifndef PICK_PLACE_MESSAGE_SRVTRANSFORM_H
#define PICK_PLACE_MESSAGE_SRVTRANSFORM_H

#include <ros/service_traits.h>


#include <pick_place/SrvTransformRequest.h>
#include <pick_place/SrvTransformResponse.h>


namespace pick_place
{

struct SrvTransform
{

typedef SrvTransformRequest Request;
typedef SrvTransformResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SrvTransform
} // namespace pick_place


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pick_place::SrvTransform > {
  static const char* value()
  {
    return "77978c20bc039a00bc9de385da9b5ab9";
  }

  static const char* value(const ::pick_place::SrvTransform&) { return value(); }
};

template<>
struct DataType< ::pick_place::SrvTransform > {
  static const char* value()
  {
    return "pick_place/SrvTransform";
  }

  static const char* value(const ::pick_place::SrvTransform&) { return value(); }
};


// service_traits::MD5Sum< ::pick_place::SrvTransformRequest> should match 
// service_traits::MD5Sum< ::pick_place::SrvTransform > 
template<>
struct MD5Sum< ::pick_place::SrvTransformRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pick_place::SrvTransform >::value();
  }
  static const char* value(const ::pick_place::SrvTransformRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pick_place::SrvTransformRequest> should match 
// service_traits::DataType< ::pick_place::SrvTransform > 
template<>
struct DataType< ::pick_place::SrvTransformRequest>
{
  static const char* value()
  {
    return DataType< ::pick_place::SrvTransform >::value();
  }
  static const char* value(const ::pick_place::SrvTransformRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pick_place::SrvTransformResponse> should match 
// service_traits::MD5Sum< ::pick_place::SrvTransform > 
template<>
struct MD5Sum< ::pick_place::SrvTransformResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pick_place::SrvTransform >::value();
  }
  static const char* value(const ::pick_place::SrvTransformResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pick_place::SrvTransformResponse> should match 
// service_traits::DataType< ::pick_place::SrvTransform > 
template<>
struct DataType< ::pick_place::SrvTransformResponse>
{
  static const char* value()
  {
    return DataType< ::pick_place::SrvTransform >::value();
  }
  static const char* value(const ::pick_place::SrvTransformResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PICK_PLACE_MESSAGE_SRVTRANSFORM_H
