// Generated by gencpp from file pick_place/SrvTransformRequest.msg
// DO NOT EDIT!


#ifndef PICK_PLACE_MESSAGE_SRVTRANSFORMREQUEST_H
#define PICK_PLACE_MESSAGE_SRVTRANSFORMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Transform.h>
#include <geometry_msgs/Transform.h>

namespace pick_place
{
template <class ContainerAllocator>
struct SrvTransformRequest_
{
  typedef SrvTransformRequest_<ContainerAllocator> Type;

  SrvTransformRequest_()
    : origin()
    , target()  {
    }
  SrvTransformRequest_(const ContainerAllocator& _alloc)
    : origin(_alloc)
    , target(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Transform_<ContainerAllocator>  _origin_type;
  _origin_type origin;

   typedef  ::geometry_msgs::Transform_<ContainerAllocator>  _target_type;
  _target_type target;





  typedef boost::shared_ptr< ::pick_place::SrvTransformRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pick_place::SrvTransformRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SrvTransformRequest_

typedef ::pick_place::SrvTransformRequest_<std::allocator<void> > SrvTransformRequest;

typedef boost::shared_ptr< ::pick_place::SrvTransformRequest > SrvTransformRequestPtr;
typedef boost::shared_ptr< ::pick_place::SrvTransformRequest const> SrvTransformRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pick_place::SrvTransformRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pick_place::SrvTransformRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pick_place

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pick_place::SrvTransformRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pick_place::SrvTransformRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pick_place::SrvTransformRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pick_place::SrvTransformRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_place::SrvTransformRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_place::SrvTransformRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pick_place::SrvTransformRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3848f0df5d35e9eee9cfb2077e99e33b";
  }

  static const char* value(const ::pick_place::SrvTransformRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3848f0df5d35e9eeULL;
  static const uint64_t static_value2 = 0xe9cfb2077e99e33bULL;
};

template<class ContainerAllocator>
struct DataType< ::pick_place::SrvTransformRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pick_place/SrvTransformRequest";
  }

  static const char* value(const ::pick_place::SrvTransformRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pick_place::SrvTransformRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Transform origin\n\
geometry_msgs/Transform target\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Transform\n\
# This represents the transform between two coordinate frames in free space.\n\
\n\
Vector3 translation\n\
Quaternion rotation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::pick_place::SrvTransformRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pick_place::SrvTransformRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.origin);
      stream.next(m.target);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SrvTransformRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pick_place::SrvTransformRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pick_place::SrvTransformRequest_<ContainerAllocator>& v)
  {
    s << indent << "origin: ";
    s << std::endl;
    Printer< ::geometry_msgs::Transform_<ContainerAllocator> >::stream(s, indent + "  ", v.origin);
    s << indent << "target: ";
    s << std::endl;
    Printer< ::geometry_msgs::Transform_<ContainerAllocator> >::stream(s, indent + "  ", v.target);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PICK_PLACE_MESSAGE_SRVTRANSFORMREQUEST_H
